version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - security

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    labels:
      - dependencies
    groups:
      frontend:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
    labels:
      - dependencies
    groups:
      backend:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly
    labels:
      - dependencies
      - containers

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - containers

  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: weekly
    labels:
      - dependencies
      - containers

  - package-ecosystem: docker
    directory: /db
    schedule:
      interval: weekly
    labels:
      - dependencies
      - containers

  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: weekly
    labels:
      - dependencies
      - containers
