/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as ChannelsIndexRouteImport } from './routes/channels.index'
import { Route as ChannelsChannelIdRouteImport } from './routes/channels.$channelId'
import { Route as ChannelsNewRouteImport } from './routes/channels.new'
import { Route as SongsSongIdRouteImport } from './routes/songs.$songId'
import { Route as VideosVideoIdRouteImport } from './routes/videos.$videoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsIndexRoute = ChannelsIndexRouteImport.update({
  id: '/channels/',
  path: '/channels/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsChannelIdRoute = ChannelsChannelIdRouteImport.update({
  id: '/channels/$channelId',
  path: '/channels/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsNewRoute = ChannelsNewRouteImport.update({
  id: '/channels/new',
  path: '/channels/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSongIdRoute = SongsSongIdRouteImport.update({
  id: '/songs/$songId',
  path: '/songs/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosVideoIdRoute = VideosVideoIdRouteImport.update({
  id: '/videos/$videoId',
  path: '/videos/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/status': typeof StatusRoute
  '/summary': typeof SummaryRoute
  '/channels/$channelId': typeof ChannelsChannelIdRoute
  '/channels/new': typeof ChannelsNewRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/channels/': typeof ChannelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/status': typeof StatusRoute
  '/summary': typeof SummaryRoute
  '/channels/$channelId': typeof ChannelsChannelIdRoute
  '/channels/new': typeof ChannelsNewRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/channels': typeof ChannelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/status': typeof StatusRoute
  '/summary': typeof SummaryRoute
  '/channels/$channelId': typeof ChannelsChannelIdRoute
  '/channels/new': typeof ChannelsNewRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/channels/': typeof ChannelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/status'
    | '/summary'
    | '/channels/$channelId'
    | '/channels/new'
    | '/songs/$songId'
    | '/videos/$videoId'
    | '/channels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/status'
    | '/summary'
    | '/channels/$channelId'
    | '/channels/new'
    | '/songs/$songId'
    | '/videos/$videoId'
    | '/channels'
  id:
    | '__root__'
    | '/'
    | '/status'
    | '/summary'
    | '/channels/$channelId'
    | '/channels/new'
    | '/songs/$songId'
    | '/videos/$videoId'
    | '/channels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatusRoute: typeof StatusRoute
  SummaryRoute: typeof SummaryRoute
  ChannelsChannelIdRoute: typeof ChannelsChannelIdRoute
  ChannelsNewRoute: typeof ChannelsNewRoute
  SongsSongIdRoute: typeof SongsSongIdRoute
  VideosVideoIdRoute: typeof VideosVideoIdRoute
  ChannelsIndexRoute: typeof ChannelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels/': {
      id: '/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof ChannelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels/$channelId': {
      id: '/channels/$channelId'
      path: '/channels/$channelId'
      fullPath: '/channels/$channelId'
      preLoaderRoute: typeof ChannelsChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels/new': {
      id: '/channels/new'
      path: '/channels/new'
      fullPath: '/channels/new'
      preLoaderRoute: typeof ChannelsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$songId': {
      id: '/songs/$songId'
      path: '/songs/$songId'
      fullPath: '/songs/$songId'
      preLoaderRoute: typeof SongsSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$videoId': {
      id: '/videos/$videoId'
      path: '/videos/$videoId'
      fullPath: '/videos/$videoId'
      preLoaderRoute: typeof VideosVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatusRoute: StatusRoute,
  SummaryRoute: SummaryRoute,
  ChannelsChannelIdRoute: ChannelsChannelIdRoute,
  ChannelsNewRoute: ChannelsNewRoute,
  SongsSongIdRoute: SongsSongIdRoute,
  VideosVideoIdRoute: VideosVideoIdRoute,
  ChannelsIndexRoute: ChannelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
