/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CopyrightRouteImport } from './routes/copyright'
import { Route as HowToUseRouteImport } from './routes/how-to-use'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThanksRouteImport } from './routes/thanks'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ChannelsIndexRouteImport } from './routes/channels.index'
import { Route as ChannelsChannelIdRouteImport } from './routes/channels.$channelId'
import { Route as ChannelsNewRouteImport } from './routes/channels.new'
import { Route as SongsSongIdRouteImport } from './routes/songs.$songId'
import { Route as VideosVideoIdRouteImport } from './routes/videos.$videoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightRoute = CopyrightRouteImport.update({
  id: '/copyright',
  path: '/copyright',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToUseRoute = HowToUseRouteImport.update({
  id: '/how-to-use',
  path: '/how-to-use',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanksRoute = ThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsIndexRoute = ChannelsIndexRouteImport.update({
  id: '/channels/',
  path: '/channels/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsChannelIdRoute = ChannelsChannelIdRouteImport.update({
  id: '/channels/$channelId',
  path: '/channels/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsNewRoute = ChannelsNewRouteImport.update({
  id: '/channels/new',
  path: '/channels/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSongIdRoute = SongsSongIdRouteImport.update({
  id: '/songs/$songId',
  path: '/songs/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosVideoIdRoute = VideosVideoIdRouteImport.update({
  id: '/videos/$videoId',
  path: '/videos/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/copyright': typeof CopyrightRoute
  '/how-to-use': typeof HowToUseRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/status': typeof StatusRoute
  '/summary': typeof SummaryRoute
  '/terms': typeof TermsRoute
  '/thanks': typeof ThanksRoute
  '/updates': typeof UpdatesRoute
  '/admin/login': typeof AdminLoginRoute
  '/channels/$channelId': typeof ChannelsChannelIdRoute
  '/channels/new': typeof ChannelsNewRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/channels/': typeof ChannelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/copyright': typeof CopyrightRoute
  '/how-to-use': typeof HowToUseRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/status': typeof StatusRoute
  '/summary': typeof SummaryRoute
  '/terms': typeof TermsRoute
  '/thanks': typeof ThanksRoute
  '/updates': typeof UpdatesRoute
  '/admin/login': typeof AdminLoginRoute
  '/channels/$channelId': typeof ChannelsChannelIdRoute
  '/channels/new': typeof ChannelsNewRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/channels': typeof ChannelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/copyright': typeof CopyrightRoute
  '/how-to-use': typeof HowToUseRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/status': typeof StatusRoute
  '/summary': typeof SummaryRoute
  '/terms': typeof TermsRoute
  '/thanks': typeof ThanksRoute
  '/updates': typeof UpdatesRoute
  '/admin/login': typeof AdminLoginRoute
  '/channels/$channelId': typeof ChannelsChannelIdRoute
  '/channels/new': typeof ChannelsNewRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/channels/': typeof ChannelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/copyright'
    | '/how-to-use'
    | '/privacy'
    | '/search'
    | '/status'
    | '/summary'
    | '/terms'
    | '/thanks'
    | '/updates'
    | '/admin/login'
    | '/channels/$channelId'
    | '/channels/new'
    | '/songs/$songId'
    | '/videos/$videoId'
    | '/channels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/copyright'
    | '/how-to-use'
    | '/privacy'
    | '/search'
    | '/status'
    | '/summary'
    | '/terms'
    | '/thanks'
    | '/updates'
    | '/admin/login'
    | '/channels/$channelId'
    | '/channels/new'
    | '/songs/$songId'
    | '/videos/$videoId'
    | '/channels'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/copyright'
    | '/how-to-use'
    | '/privacy'
    | '/search'
    | '/status'
    | '/summary'
    | '/terms'
    | '/thanks'
    | '/updates'
    | '/admin/login'
    | '/channels/$channelId'
    | '/channels/new'
    | '/songs/$songId'
    | '/videos/$videoId'
    | '/channels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CopyrightRoute: typeof CopyrightRoute
  HowToUseRoute: typeof HowToUseRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  StatusRoute: typeof StatusRoute
  SummaryRoute: typeof SummaryRoute
  TermsRoute: typeof TermsRoute
  ThanksRoute: typeof ThanksRoute
  UpdatesRoute: typeof UpdatesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ChannelsChannelIdRoute: typeof ChannelsChannelIdRoute
  ChannelsNewRoute: typeof ChannelsNewRoute
  SongsSongIdRoute: typeof SongsSongIdRoute
  VideosVideoIdRoute: typeof VideosVideoIdRoute
  ChannelsIndexRoute: typeof ChannelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright': {
      id: '/copyright'
      path: '/copyright'
      fullPath: '/copyright'
      preLoaderRoute: typeof CopyrightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-use': {
      id: '/how-to-use'
      path: '/how-to-use'
      fullPath: '/how-to-use'
      preLoaderRoute: typeof HowToUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanks': {
      id: '/thanks'
      path: '/thanks'
      fullPath: '/thanks'
      preLoaderRoute: typeof ThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels/': {
      id: '/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof ChannelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels/$channelId': {
      id: '/channels/$channelId'
      path: '/channels/$channelId'
      fullPath: '/channels/$channelId'
      preLoaderRoute: typeof ChannelsChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels/new': {
      id: '/channels/new'
      path: '/channels/new'
      fullPath: '/channels/new'
      preLoaderRoute: typeof ChannelsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$songId': {
      id: '/songs/$songId'
      path: '/songs/$songId'
      fullPath: '/songs/$songId'
      preLoaderRoute: typeof SongsSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$videoId': {
      id: '/videos/$videoId'
      path: '/videos/$videoId'
      fullPath: '/videos/$videoId'
      preLoaderRoute: typeof VideosVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CopyrightRoute: CopyrightRoute,
  HowToUseRoute: HowToUseRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  StatusRoute: StatusRoute,
  SummaryRoute: SummaryRoute,
  TermsRoute: TermsRoute,
  ThanksRoute: ThanksRoute,
  UpdatesRoute: UpdatesRoute,
  AdminLoginRoute: AdminLoginRoute,
  ChannelsChannelIdRoute: ChannelsChannelIdRoute,
  ChannelsNewRoute: ChannelsNewRoute,
  SongsSongIdRoute: SongsSongIdRoute,
  VideosVideoIdRoute: VideosVideoIdRoute,
  ChannelsIndexRoute: ChannelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
